[package]
name = "nexora-shield"
description = "Command-line interface for Nexora Shield."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
nexora-shield-core = { path = "../shield-core" }

[lints]
workspace = true
