[package]
name = "nexora-shield"
description = "Command-line interface for Nexora Shield."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
nexora-shield-integrity = { path = "../shield-integrity" }
nexora-shield-crypto = { path = "../shield-crypto" }
nexora-shield-dex = { path = "../shield-dex" }
nexora-shield-core = { path = "../shield-core" }
nexora-shield-package = { path = "../shield-package" }

[lints]
workspace = true
